// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoGnD_CdDR1sliHGELmMYA05CpVnFI-qk',
    appId: '1:172378950844:web:6ad6ea505cacc8e5d554b9',
    messagingSenderId: '172378950844',
    projectId: 'pomodoro-2ec44',
    authDomain: 'pomodoro-2ec44.firebaseapp.com',
    storageBucket: 'pomodoro-2ec44.firebasestorage.app',
    measurementId: 'G-P4XCEFGGQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHtGMYm_kPmojus2euzdYzKnuGttnw81s',
    appId: '1:172378950844:android:905ba96e3ffcab59d554b9',
    messagingSenderId: '172378950844',
    projectId: 'pomodoro-2ec44',
    storageBucket: 'pomodoro-2ec44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLSVtyEpW2EDETjY0es2H5x0iFcDUAkp4',
    appId: '1:172378950844:ios:a93185621d24e867d554b9',
    messagingSenderId: '172378950844',
    projectId: 'pomodoro-2ec44',
    storageBucket: 'pomodoro-2ec44.firebasestorage.app',
    iosBundleId: 'com.example.pomodoroDesktop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLSVtyEpW2EDETjY0es2H5x0iFcDUAkp4',
    appId: '1:172378950844:ios:a93185621d24e867d554b9',
    messagingSenderId: '172378950844',
    projectId: 'pomodoro-2ec44',
    storageBucket: 'pomodoro-2ec44.firebasestorage.app',
    iosBundleId: 'com.example.pomodoroDesktop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoGnD_CdDR1sliHGELmMYA05CpVnFI-qk',
    appId: '1:172378950844:web:d2d20fb08b506eb2d554b9',
    messagingSenderId: '172378950844',
    projectId: 'pomodoro-2ec44',
    authDomain: 'pomodoro-2ec44.firebaseapp.com',
    storageBucket: 'pomodoro-2ec44.firebasestorage.app',
    measurementId: 'G-2FBHEJVV1S',
  );
}
